### ISSUE TITLE
Fix issue for when there is no solution

### ISSUE THREAD

**Issue by Jcorb08** [Jcorb08/ASE#32]
Fix an issue where it solves the board even when there is no solution, have a prompt or visual that shows there is no solution and then allows a reset after this.

**Comment by peymosiec01** [comment]
https://user-images.githubusercontent.com/7995928/204479665-fe2f689a-dd11-4cf2-82d9-872b6018c659.mov


@Jcorb08 the notification has been designed; awaiting update from the backend code

**Comment by Jcorb08** [comment]
Superb love it!
