### ISSUE TITLE
Building basic frontend that represents wireframe

### ISSUE THREAD

**Issue by Jcorb08** [Jcorb08/ASE#9]
Create the basic HTML structure as to where everything will go in Angular, all the buttons can be dummy for now

**Comment by peymosiec01** [comment]
@Jcorb08  @jon4444 Please review the wireframe frontend work on the `structure-the-app` branch and give thumbs-up if it's okay to merge to the `master` branch for continuous development



![Image](https://user-images.githubusercontent.com/7995928/198145392-5eeb9a93-46ea-453c-b107-5d8a6baf4a51.png)

**Comment by Jcorb08** [comment]
> @Jcorb08 @jon4444 Please review the wireframe frontend work on the `structure-the-app` branch and give thumbs-up if it's okay to merge to the `master` branch for continuous development
> 
> ![Image](https://user-images.githubusercontent.com/7995928/198145392-5eeb9a93-46ea-453c-b107-5d8a6baf4a51.png)

Sorry for not replying sooner looks great!

**Comment by jon4444** [comment]
looks really good
